### ISSUE TITLE
[Bug] Missing setup files for creating embedding

### ISSUE THREAD

**Issue by toptechie156** [fjzzq2002/is-my-problem-new#2]
Hey, love the product ❤️

but `src/build_summary` file is missing in current codebase. Due to which search is not working even after running the server 

I can see it got missing after the **Update (2024/7/16)**

I am helping my professor to  for a contest at our uni this weekend and needed to test similarity with our past private uni problems to prevent plaigarism. 

Hopefully this gets resolved in time and I get to save my TA'ship xD

**Comment by toptechie156** [comment]
@fjzzq2002  This is the error that I get while searching which suggests that embeddings are empty


> Traceback (most recent call last):
  File "is-my-problem-new/src/ui.py", line 329, in async_querier_wrapper
    result = await querier_i18n(locale, *args)
  File "is-my-problem-new/src/ui.py", line 93, in querier_i18n
    nearest = await loop.run_in_executor(executor, db.query_nearest, emb, 5000)
  File "/usr/local/Cellar/python@3.9/3.9.19/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "is-my-problem-new/src/embedder.py", line 177, in query_nearest
    sims = np.max(self.arr @ emb.T, axis=1)
ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 1024 is different from 0)

**Comment by fjzzq2002** [comment]
Ah I'm sooooo sorry about that ;_; didn't check github notifications at all

Did you figure this out? I think the file is still there, so maybe you just need to first run `build_summary`, and then `embedder`? If something still goes wrong let me know!

**Comment by toptechie156** [comment]
No problem, appreciate the reply.

Unfortunately, not resolved yet 😔.  Not able to figure out how to run `embedder` without `build_embedding`. Which results in the error on searching in UI that I mentioned in  https://github.com/fjzzq2002/is-my-problem-new/issues/2#issuecomment-2392346510

**Comment by fjzzq2002** [comment]
You should be able to just do `python -m src.embedder` or similar. Are you seeing `*.vopkl` files? Also just in case maybe you can double check if your json's are following the format [here](https://github.com/fjzzq2002/is-my-problem-new/blob/main/problems/1000.json).

**Comment by toptechie156** [comment]
Thanks! this worked, I feel dumb enough to not have figured this out on my own 😆
