### ISSUE TITLE
SIR Site has been down please restart it sir.

### ISSUE THREAD

**Issue by Eli4479** [fjzzq2002/is-my-problem-new#3]
SIR Site has been down please restart it sir.

it been loading and not getting live

**Comment by fjzzq2002** [comment]
Thanks I'm debugging it ;_;

**Comment by fjzzq2002** [comment]
Fixed https://github.com/fjzzq2002/is-my-problem-new/commit/9e6feba786d86a9942d12ec0309d0adc2c00811d
